# Generated by Django 5.2.14 on 2026-06-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='bank',
                    new_name='bank_bank_na_a9ac66_idx',
                    old_name='bank_bank_na_e0d24a_idx',
                ),
                migrations.RenameIndex(
                    model_name='baserate',
                    new_name='base_rate_country_c8b7ac_idx',
                    old_name='base_rate_country_1ff6e8_idx',
                ),
                migrations.RenameIndex(
                    model_name='baserate',
                    new_name='base_rate_created_535d3e_idx',
                    old_name='base_rate_created_52e607_idx',
                ),
                migrations.RenameIndex(
                    model_name='country',
                    new_name='country_country_252656_idx',
                    old_name='country_countr_223010_idx',
                ),
                migrations.RenameIndex(
                    model_name='depositrate',
                    new_name='deposit_rat_bank_id_7708bb_idx',
                    old_name='deposit_rat_bank_id_536c8f_idx',
                ),
                migrations.RenameIndex(
                    model_name='depositrate',
                    new_name='deposit_rat_prime_r_e80168_idx',
                    old_name='deposit_rat_prime_r_e501b9_idx',
                ),
            ],
        ),
    ]
