FROM flink:1.18.1-java11

# Install Python and wget
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev wget && \
    rm -rf /var/lib/apt/lists/*

# Set python3 as default
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install PyFlink and dependencies
RUN pip3 install --no-cache-dir apache-flink==1.18.1 requests beautifulsoup4 kafka-python psycopg2-binary python-dotenv

# Download Flink Connectors (Kafka, JDBC, Postgres)
RUN wget https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.0.1-1.18/flink-sql-connector-kafka-3.0.1-1.18.jar -P /opt/flink/lib/ && \
    wget https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc/3.1.2-1.18/flink-connector-jdbc-3.1.2-1.18.jar -P /opt/flink/lib/ && \
    wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.2/postgresql-42.7.2.jar -P /opt/flink/lib/

RUN chmod 644 /opt/flink/lib/*.jar
WORKDIR /opt/flink
