# Generated by Django 5.2.14 on 2026-06-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossary',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='glossarycategory',
            options={'managed': False},
        ),
    ]
