# Generated by Django 5.2.14 on 2026-06-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_alter_glossary_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='glossary',
                    table='"Glossary"',
                ),
                migrations.AlterModelTable(
                    name='glossarycategory',
                    table='"GlossaryCategory"',
                ),
            ],
        ),
    ]
