# Generated by Django 5.2.14 on 2026-06-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_sync_table_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='glossary',
            table='glossary',
        ),
        migrations.AlterModelTable(
            name='glossarycategory',
            table='glossary_category',
        ),
    ]
