# Generated by Django 5.2.14 on 2026-06-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondsMaster',
            fields=[
                ('isin_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bond_name', models.CharField(max_length=255)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('coupon_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('issue_amount', models.BigIntegerField(blank=True, null=True)),
                ('bond_type', models.CharField(blank=True, max_length=255, null=True)),
                ('seniority', models.CharField(blank=True, max_length=255, null=True)),
                ('call_put_option', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_cycle', models.CharField(blank=True, max_length=255, null=True)),
                ('guarantee_status', models.CharField(blank=True, max_length=255, null=True)),
                ('underwriter', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_rating', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bonds_master',
                'managed': False,
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='bond',
                    new_name='bond_bond_na_f64382_idx',
                    old_name='bond_bond_na_03fef6_idx',
                ),
                migrations.RenameIndex(
                    model_name='bond',
                    new_name='bond_short_n_0a4424_idx',
                    old_name='bond_short_n_8d3189_idx',
                ),
                migrations.RenameIndex(
                    model_name='bond',
                    new_name='bond_issuer__a713ae_idx',
                    old_name='bond_issuer__c6e37f_idx',
                ),
                migrations.RenameIndex(
                    model_name='bond',
                    new_name='bond_bond_ty_5a0322_idx',
                    old_name='bond_bond_ty_afb377_idx',
                ),
                migrations.RenameIndex(
                    model_name='bond',
                    new_name='bond_rating__252d61_idx',
                    old_name='bond_rating__83914b_idx',
                ),
                migrations.RenameIndex(
                    model_name='bond',
                    new_name='bond_maturit_e613b4_idx',
                    old_name='bond_maturit_aa0e5f_idx',
                ),
                migrations.RenameIndex(
                    model_name='bondmarketdata',
                    new_name='bond_market_bond_id_170340_idx',
                    old_name='bond_market_bond_id_eb4c3d_idx',
                ),
                migrations.RenameIndex(
                    model_name='bondmarketdata',
                    new_name='bond_market_base_da_1a8313_idx',
                    old_name='bond_market_base_da_7221ab_idx',
                ),
                migrations.RenameIndex(
                    model_name='bondmarketdata',
                    new_name='bond_market_ytm_9cec2a_idx',
                    old_name='bond_market_ytm_700207_idx',
                ),
                migrations.RenameIndex(
                    model_name='bondmarketdata',
                    new_name='bond_market_trading_29c338_idx',
                    old_name='bond_market_trading_cfa8f5_idx',
                ),
                migrations.RenameIndex(
                    model_name='bondoptionexercise',
                    new_name='bond_option_option__65ab73_idx',
                    old_name='bond_option_option__9d7739_idx',
                ),
                migrations.RenameIndex(
                    model_name='creditrating',
                    new_name='credit_rati_rating__555364_idx',
                    old_name='credit_rati_rating__04e2e5_idx',
                ),
                migrations.RenameIndex(
                    model_name='creditrating',
                    new_name='credit_rati_rating__5748cf_idx',
                    old_name='credit_rati_rating__b0e1f2_idx',
                ),
                migrations.RenameIndex(
                    model_name='issuer',
                    new_name='issuer_issuer__b0f501_idx',
                    old_name='issuer_issuer__4e9f0d_idx',
                ),
            ],
        ),
    ]
