# Generated by Django 5.2.14 on 2026-06-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_latest_bond_market_data_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bond',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bondcashflowrule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bondmarketdata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bondoptionexercise',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bondtype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='creditrating',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='guaranteestatus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='issuer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='seniority',
            options={'managed': False},
        ),
    ]
