FROM docker.elastic.co/logstash/logstash:8.13.4

RUN mkdir -p /usr/share/logstash/vendor/jar/jdbc \
    && curl -fsSL https://jdbc.postgresql.org/download/postgresql-42.7.4.jar \
      -o /usr/share/logstash/vendor/jar/jdbc/postgresql.jar
