# Generated by Django 5.2.14 on 2026-06-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='userbond',
                    new_name='user_bond_user_id_a01259_idx',
                    old_name='user_bond_user_id_7b7ea7_idx',
                ),
                migrations.RenameIndex(
                    model_name='userbond',
                    new_name='user_bond_bond_id_eaac4d_idx',
                    old_name='user_bond_bond_id_daf87d_idx',
                ),
            ],
        ),
    ]
