# Generated by Django 5.2.14 on 2026-06-24 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_alter_bond_options_alter_bondcashflowrule_options_and_more'),
        ('portfolios', '0002_sync_index_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bond', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_bonds', to='bonds.bond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_bonds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_bond',
                'indexes': [models.Index(fields=['user'], name='favorite_bo_user_id_01ad15_idx'), models.Index(fields=['bond'], name='favorite_bo_bond_id_bfba47_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'bond'), name='uniq_user_favorite_bond')],
            },
        ),
    ]
