# Generated by Django 5.2.14 on 2026-06-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_article',
                'managed': False,
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='news',
                    new_name='news_publish_b01c8c_idx',
                    old_name='news_publish_a1f8fb_idx',
                ),
                migrations.RenameIndex(
                    model_name='news',
                    new_name='news_source__e41e38_idx',
                    old_name='news_source__f3d10a_idx',
                ),
                migrations.RenameIndex(
                    model_name='news',
                    new_name='news_title_e65376_idx',
                    old_name='news_title_593401_idx',
                ),
                migrations.RenameIndex(
                    model_name='newsprovider',
                    new_name='news_provid_provide_2471d0_idx',
                    old_name='news_provid_provider_592f19_idx',
                ),
            ],
        ),
    ]
