# Generated by Django 5.2.14 on 2026-06-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='newsprovider',
            options={'managed': False},
        ),
    ]
