FROM apache/airflow:2.7.1

USER root
# Spark 실행에 필요한 Java 설치
RUN apt-get update && \
    apt-get install -y --no-install-recommends default-jre && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow
