FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
# Java is required for PySpark
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    default-jre \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN pip install --no-cache-dir --upgrade pip setuptools wheel

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Default command
CMD ["python", "producer/bond_to_csv.py"]
